### PR TITLE
Update template URL to a stable URL

### PR DESCRIPTION
**Pull request by illicitonion**
BCR appears to enforce this now

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]

**Comment by illicitonion** [comment]
Sorry @kormide I don't think I see a reference in that file that isn't already updated - can you quote the text you're looking to update? Thanks!

**Comment by kormide** [comment]
> here

This line: https://github.com/bazel-contrib/publish-to-bcr/blob/main/templates/README.md?plain=1#L80

**Comment by illicitonion** [comment]
I think that's the line currently edited in this PR?

**Comment by kormide** [comment]
Doh, I thought that was the template file 😅 . Could you update the template file at `templates/.bcr/source.template.json`?

**Comment by illicitonion** [comment]
😂 Done! Thanks!

**Review by kormide — APPROVED** [review]

**Pull request merged**
