### PR TITLE
Give release archive workflows more time

### PR DESCRIPTION
**Pull request by ouillie**
Addresses #140.

### CODE REVIEW

**Comment by ouillie** [comment]
Well I tried to craft a test for this, but I've never used `jest` before. I was surprised to learn that something as basic as a matcher with an arbitrary predicate was something I had to implement myself :shrug: and apparently I didn't do it right. Would highly appreciate somebody with some Typescript / `jest` experience explaining where I erred.

**Comment by ouillie** [comment]
Ok, this is now ready for review.

**Review by kormide — APPROVED** [review]
LGTM. Thanks for the contribution and nice work with the predicate.

**Review by kormide — CHANGES_REQUESTED** [review]
@ouillie Are you able to run the e2e tests locally? It looks like the test `[snapshot] error email for incorrect strip prefix in multi module repo` now times out due to the delay. We'll want a way to set a shorter delay for these tests.

**Comment by kormide** [comment]
I would be fine with just setting an env var during testing and checking for it in the release archive code.

**Comment by ouillie** [comment]
The e2e test fail for me even on the upstream main branch, so I just ignored them on my branch. Is there some setup I'm missing? I'm assuming you guys have some credentials or something that don't get distributed publicly.

**Comment by ouillie** [comment]
Just cuz I can't run it locally doesn't mean I can't try to fix it though :)

**Review by kormide — APPROVED** [review]

**Comment by ouillie** [comment]
Thanks @kormide. Do you know when this will be available in production?

**Comment by kormide** [comment]
> Thanks @kormide. Do you know when this will be available in production? I'm going to wait to kick off my next release until I know it'll work.

I already deployed it so it's ready for your next release!

**Pull request merged**
